checks:
  RDF:
    LeadingOrTrailingSpaceCheck: false
    NamespaceHijackingCheck: false
    SeparatorOmittedInNamespaceCheck: false
  RDFS:
    UnconnectedClassCheck: false
    MissingDescriptionCheck: false
    MissingLabelCheck: false
  OWL:
    OntologyIriOboConformanceCheck: false
    SynonymsAsClassesCheck: false
    UnconnectedClassCheck: false
